###
POST http://localhost:8081/api/v1/users HTTP/1.1
Content-Type: application/json

{
  "name": "Bruno Toppen",
  "username": "brxlx",
  "password": "123"
}

###
POST http://localhost:8081/api/v1/tasks HTTP/1.1
Content-Type: application/json
Authorization: Basic brxlx 123

{
 "description": "Tarefa para fazer alguma coisa",
 "title": "Fazer alguma coisa",
 "priority": "high",
 "startAt": "2023-10-15T19:00:00",
 "endAt": "2023-10-15T20:00:00"
}

###
GET  http://localhost:8081/api/v1/tasks HTTP/1.1
Content-Type: application/json
Authorization: Basic brxlx 123


###
PUT http://localhost:8081/api/v1/tasks/9a2e5639-ce19-4d3f-b1d4-82e9b730f085
Content-Type: application/json
Authorization: Basic brxlx 123

{
 "description": "Alter Tarefa para fazer alguma coisa",
 "title": "Alter fazer alguma coisa"

}