###
POST http://localhost:8081/api/v1/users HTTP/1.1
Content-Type: application/json

{
  "name": "Bruno Toppen",
  "username": "brxlx",
  "password": "123"
}

###
POST http://localhost:8081/api/v1/tasks HTTP/1.1
Content-Type: application/json
Authorization: Basic brxlx 123

{
 "description": "Tarefa para fazer alguma coisa",
 "title": "Fazer alguma coisa",
 "priority": "high",
 "startAt": "2023-10-12T19:00:00",
 "endAt": "2023-10-12T20:00:00"
}